workflows:
  build_ios:
    name: MacroMaster iOS Build
    max_build_duration: 60
    environment:
      vars:
        PROJECT_PATH: "MacroMaster"
        SCHEME: "MacroMaster"
      groups:
        - app_store_credentials
    scripts:
      - name: Build IPA
        script: |
          set -e
          # Use xcodebuild to archive and export
          xcodebuild -project MacroMaster.xcodeproj -scheme MacroMaster -configuration Release -archivePath build/MacroMaster.xcarchive archive
          xcodebuild -exportArchive -archivePath build/MacroMaster.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build
    artifacts:
      - build/*.ipa
